baseURL = "https://iepathos.github.io"
languageCode = "en-us"
title = "Party Parrot Games"
theme = "keepit"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""
disqusShortname = "yourdiscussshortname"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[markup.goldmark.renderer]
  unsafe = true

[Permalinks]
 posts = "/:year/:filename/"

# [menu]

  # [[menu.main]]
  #   name = "Save The Llama"
  #   url = "/stl"
  #   weight = 1

  # [[menu.main]]
  #   name = "About"
  #   url = "/about"
  #   weight = 2

   # [[menu.main]]
   #  name = "Blog"
   #  url = "/posts/"
   #  weight = 3

[params]
    since = 2021
    author = "Party Parrot Games"               # Author's name
    subtitle = "Keep the party going"       # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other
    dateFormatToUse = "" # set date format, default "2 January 2006"
    
    google_verification = ""
    bing_verification = ""
    yandex_verification = ""
    pinterest_verification = ""
    baidu_verification = ""

    # avatar = "/images/spacemonkey_logo_dribble.jpg" #comment it to use gravatar
    socialShare = true

    description = "Party Parrot Games is an indie game startup." # site description
    keywords = "video games, development, indie, tower defense, save the llama, stl, startup, picnic panic" # site keywords

    license= 'All rights reserved.'

[params.gravatar]
    #email = "example@gmail.com"   #uncomment and insert your email address to use gravatar


[params.social]
    Discord = "https://discord.gg/R3zXZ8Whck"
    # GitHub = "xxxx"
    # Linkedin = "xxxx"
    Twitter = "PartyParrotGame"
    #Instagram = "xxxx"
    Email   = "partyparrotgames@gmail.com"
    Facebook = "partyparrotgames"
    #Telegram = "xxxx"
    #Medium = "xxxx"
    #Gitlab = "xxxx"
    #Youtubelegacy = "xxxx"
    #Youtubecustom = "xxxx"
    Youtubechannel = "UCmQUr9Ts83yKhlK-LId5O_A"
    #Tumblr ="xxxx"
    #Quora = "xxxx"
    #Keybase = "xxxx"
    #Pinterest = "xxxx"
    Reddit = "PartyParrotGames"
    #Codepen = "xxxx"
    #Bitbucket = "xxxx"
    #Stackoverflow = "xxxxx"
    #Weibo = "xxxx"
    #Odnoklassniki = "xxxx"
    #VKontakte = "xxxx"
    #Flickr = "xxxx"
    #Xing = "xxxx"
    #Snapchat = "xxxx"
    #Soundcloud = "xxxx"
    #Spotify = "xxxx"
    #Bandcamp = "xxxx"
    #Paypal = "xxxx"
    #Fivehundredpx = "xxxx"
    #Mix = "xxxx"
    #Goodreads = "xxxx"
    #Lastfm = "xxxx"
    #Foursquare = "xxxx"
    #Hackernews = "xxxx"
    #Kickstarter = "xxxx"
    #Patreon = "xxxx"
    Steam = "https://store.steampowered.com/search/?publisher=Party%20Parrot%20Games"
    Twitch = "partyparrotgames"
    #Strava = "xxxx"
    #Skype = "xxxx"
    #Whatsapp = "xxxx"
    #Zhihu = "xxxx"
    #Douban = "xxxx"
    #Angellist = "xxxx"
    #Slidershare = "xxxx"
    #Jsfiddle = "xxxx"
    #Deviantart = "xxxx"
    #Behance = "xxxx"
    #Dribble = "xxxx"
    #Wordpress = "xxxx"
    #Vine = "xxxx"
    #Googlescholar = "xxxx"
    #Researchgate = "xxxx"
    #Mastodon = "xxxx"
    #Thingiverse = "xxxx"

[params.share]
Twitter = true
Facebook = true
Reddit = true
# Linkedin = true
Pinterest = true
#HackerNews = true
#Mix = true
#Tumblr = true
#VKontakte = true
#Douban = true
#Weibo = true

# Used only for Seo schema
copyright = "All rights reserved."

[author]
  name = "Glen Baker & Adam Clarke"

  [params.publisher]
    name = "Glen Baker & Adam Clarke"

    [params.publisher.logo]
      url = "logo.png"
      width = 127
      height = 40

  [params.logo]
    url = "logo.png"
    width = 127
    height = 40

  [params.image]
    url = "cover.png"
    width = 800
    height = 600

[params.gitalk]
owner = ""       # Your GitHub ID
repo = ""        # The repo to store comments
clientId = ""    # Your client ID
clientSecret = "" # Your client secret

[params.valine]
  enable = false
  language = 'en'
  appId = 'your appId'
  appKey = 'your appKey'
  notify = false  # mail notifier , https://github.com/xCss/Valine/wiki
  verify = false # Verification code
  avatar = 'mm'
  placeholder = 'your comments ...'
  visitor = true

[params.utterances]       # https://utteranc.es/
    owner = ""              # Your GitHub ID
    repo = ""               # The repo to store comments

[params.gitment]          # Gitment is a comment system based on GitHub issues. see https://github.com/imsun/gitment
    owner = ""              # Your GitHub ID
    repo = ""               # The repo to store comments
    clientId = ""           # Your client ID
    clientSecret = ""       # Your client secret
